mysql/files/my.cnf
Options in my.cnf are not sorted at this moment which introduces unnecessary
changes whenever the file is being rewritten.
=> Sort options in my.cnf

mysql/database.sls, pillar.example
You can now optionally specify a `template: jinja` pillar and the source will be treated as a Jinja template.
This essentially extends the templating of the `file` state to SQL schemas.
Added a pillar.example showing how to do it, e.g.
```yaml
mysql:
schema:
baz:
load: True
source: salt://mysql/files/baz.schema.tmpl
template: jinja
```
=> Added ability for SQL Schemas to be templates

mysql/database.sls, mysql/remove_test_database.sls, mysql/server.sls, mysql/user.sls, pillar.example
In our setup we mostly use mysql on localhost but sometimes it's on another server (Amazon rds for example) and it would be nice to be able to control the users and databases using this same state instead of having to code it separately. This just adds possibility of overriding the host with pillar data and defaults lo localhost otherwise
=> Add possibility of using another host (for db and user management)

mysql/user.sls
If no root_password pillar was set, adding users was not possible since it did not use the server_id as password
=> Use default root_password if not set

mysql/server.sls
The debconf functionality does not work if the mysql.server variable has been used in the pillar to change the package name.
This fix has been tested on `percona-server-server` package which is filesystem compatible with `mysql-server`.
=> Use mysql.server variable instead of hardcoded mysql-server for debconf

mysql/server.sls
On RHEL, the current mysql_root_user variable is not used when configuring the MySQL server. As a result, using a username other than root causes failures of subsequent functions such as mysql_user.absent and mysql_db_*.
=> Fix RedHat MySQL admin root username pillar setup.

mysql/database.sls
Fixes issue with import of databases when using non-standard root user account.
=> Fix database administrative user within database import command

mysql/server.sls
Arch linux does not automatically create the base mysql data directory structure and table. This patch calls mysql_install_db script to create it.
=> Archlinux - create initial mysql data directory

mysql/server.sls
When OS family is other than "Arch" mysql_install_datadir will be a empty dictionary. Related with PR merge: d6a4a1a21474570e1837924c7e46b1b5d63afff3
=> Fix empty "mysql_install_datadir" dict when OS family is not "Arch"

mysql/database.sls, mysql/remove_test_database.sls, mysql/salt-user.sls, mysql/server.sls, mysql/user.sls, pillar.example
Some use cases for this are
* no need to have the root password in plain text in pillar (we can use a hash instead)
* useful for auditing when you can distinguish between salt accesses and actual root accesses
The main tricky thing here is how to make it work in the most common scenarios, like:
* an existing setup using root with password defined in pillar
* a fresh setup using root without any password
* an existing setup using root without password (e.g. with socket authentication)
* a second-run setup already using the salt user and only having a password hash for root
* a setup that keeps on using root instead of the salt user
I tried to cover as much ground as possible here, but I'm not entirely sure I got the service dependencies right. Especially the deletion of the anonymous users …
=> Add states for optional dedicated salt user instead of root.

mysql/database.sls
Current databases state allows databases to be created on remote servers, but won't load schemas. Added hostname option to load state to handle.
=> Allow loading into remote databases

mysql/user.sls, pillar.example
This allows for more dynamically defining which database hosts a user should be added to, so you don't have to update the pillar data every time you add a new db server to your application setup.
=> Add support for fetching user hosts from salt mine.

mysql/config.sls, mysql/server.sls
the config file update depends on the parent directory /etc/mysql being present, which is created as part of the mysql-server package installation. therefore, the mysqld state is split up for debian environments into the package installation and the mysqld configuration. this allows to set the pkg installation as a requirement for the config file management and to set the config file management as a requirement for the mysqld service management
=> fixed /etc/mysql/my.cnf creation failure in debian

mysql/server.sls
A small fix in server.sls with archlinux not using the right required package name.
=> fix archlinux package

mysql/defaults.yaml
I was playing with this on Fedora 23, and the package that is installed by default no longer exists.
I haven't looked into why my override wasn't working as intended yet though.
=> This default is not overridden properly for some reason

mysql/defaults.yaml
update default of pid-file to pid_file. Otherwise pid-file ends up always
in server.cnf and cannot be overriden, since all keys are modified to
use only underscores.
=> prevent multiple configuration of pid file

mysql/defaults.yaml
wsrep_notify_cmd cannot be without a value
=> galera: fix invalid default

mysql/user.sls
if ssl_option is not False, mysql_grant.present adds "REQUIRE" to the
grant command but since all the ssl sub options are false or missing,
there is a null string appended to the requirements. This causes the
grant command to fail.
This tests to see if ssl or X509 are set. If they're not, it skips the
entire ssl_option section leaving ssl_option==False to prevent that
error.
Fixes #131
=> Fix broken GRANT when not ssl

mysql/server.sls
Some distros set the environment variable for the temp directory to
/tmp/$USER which is owned by $USER mode 700. This prevents the
mysql user from being able to access the temporary files it needs.
=> Set environment temp directory to /tmp

mysql/database.sls, pillar.example
This simplifies how schema files can be templated, especially when using
the same template to set up multiple databases on the same server.
=> Feature setting the template context from the mysql:schema pillar

mysql/server.sls
@aboe76 noted a compile error on Arch using pkg.version as the check for 5.7+. His recommendation was to adjust it to mysql.version as this works on Arch.
Tested on Redhat and solution still works with this check.
=> Adjust check to mysql.version due to compile fail on Arch.

README.rst, mysql/repo.sls
This commits my initial work for adding support for the official MySQL repositories.
Completed:
- Adding official MySQL repository to RHEL with MySQL 5.7 by default.
- Require repo state finishes before package installation if included.
TODOS:
- Add support for Debian, Ubuntu, Fedora and Suse packages on http://repo.mysql.com/
- Allow preferred version to trigger enabling/disabling of appropriate repos. Repos for 5.5, 5.6 and 8.0 are installed with package.
=> Add official repo state

mysql/salt-user.sls, mysql/server.sls
The formula failed with `Cannot extend ID 'mysql_root_password' in 'base:mysql.salt-user'.`. It was caused by `require_in` definitions in the `salt-user` state using `mysql_user: mysql_root_password`. That state is only defined in `server.sls` for RHEL & Suse (https://github.com/saltstack-formulas/mysql-formula/blob/master/mysql/server.sls#L34). The state was missing on debian, thus raising the exception. 
The PR is practically wrapping all of those with conditionals.
=> Fixed formula on Debian where mysql_root_password state is not present. 

mysql/files/my.cnf, pillar.example
Fix for https://github.com/saltstack-formulas/mysql-formula/issues/67
example:
```
binlog-ignore-db:
- mysql
- sys
- information_schema
- performance_schema
```
=> add ability to specify repeating keys

mysql/defaults.yaml, mysql/server.sls
mysql.server formula failed on gentoo because of hard-coded pid-file (pid_file is not detected as declared for gentoo defaults.yaml because the variable name for the pid-file is hard-coded in the init.d script installed by standard dev-db/mysql ebuild as pid-file (not pid_file)).
mysql.server formula also failed because it was missing the `emerge --config dev-db/mysql` step. This commit adds this as an alternative mysql_initialize step for the gentoo os_family.
=> mysql.server formula fixes for gentoo

mysql/config.sls, mysql/server.sls
This fixes issue #127 
Without this patch your unable to modify */etc/mysql/my.cnf* without installing mysql.server.
This patch removes that requirement.
@gravyboat pinging you for the merge.
=> Fix mysql.config for client only installations.

mysql/server.sls
When in MariaDB a new datadir is used, then the new datadir must exist before the service can start. When the service start it will install an empty database in the created dir. It doesn't work with 
This fix add a state which create an empty datadir, before the service will start.
=> Fix setting datadir to alternate dir with mariadb

mysql/server.sls
This is needed for correctly setting the root password when installing mariadb and addresses #43. 
The `mysql-server/root_password` and `mysql-server/root_password_again` debconf keys are used by mysql-server and mariadb-server and are referenced directly in the postinst scripts of the respective package.
=> Hardcode 'mysql-server' as debconf base path for root password

mysql/defaults.yaml
This will fix opensuse/suse grains for this formula, see https://github.com/saltstack-formulas/mysql-formula/issues/156
=> fix SUSE os grain

mysql/repo.sls
New hash for http://repo.mysql.com/RPM-GPG-KEY-mysql is md5=472a4a4867adfd31a68e8c9bbfacc23d
=> Update hash for MySQL community server RPM repo

mysql/init.sls, mysql/server.sls
mysql-formula should create the salt_user. Also, add a dependency to avoid failures on the first run.
This fixes https://github.com/saltstack-formulas/mysql-formula/issues/157
=> Fix two issues when using a salt_user

mysql/user.sls
From this formula, I can declare users on an external mysql server, but not grants:
> ----------
ID: mysql_user_sync_10.0.0.1
Function: mysql_user.present
Name: sync
Result: True
Comment: User sync@10.0.0.1 is already present with the desired password
Started: 09:50:15.029645
Duration: 15.726 ms
Changes:   
----------
ID: mysql_user_sync_10.0.0.1_grants
Function: mysql_grants.present
Name: sync
Result: False
Comment: MySQL Error 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Started: 09:50:15.045862
Duration: 0.925 ms
Changes:
=> honorate mysql:server:host as in user declaration

mysql/server.sls
Fixes #152 by leveraging the nature of dicts in Python, thereby avoiding any duplicate IDs. Salt (and Jinja too eventually in its core) has introduced a `unique` filter (albeit currently [undocumented](https://github.com/saltstack/salt/issues/42717)) in v2017.5 but this would require the formula to move to that version or above.
This solves the problem in a backwards compatible way.
=> Fix duplicate ID if fqdn is localhost/localhost.localdomain

README.rst, mysql/defaults.yaml, mysql/remove_test_database.sls, mysql/server.sls, mysql/server_checks.sls, pillar.example
- Fixed minor documentation error in `pillar.example`
- FreeBSD uses `py27-pymysql` instead of `pymysql` (at least on 10.3)
- FreeBSD uses the same way to set the root password as RedHat and Suse
- New state `mysql.server_checks` prevents a "silent security fail" when no root password is set.
=> FreeBSD support & opt-in state to enforce root password

mysql/defaults.yaml, mysql/server.sls
This allows users to use this formula on Debian releases after (and including) stretch, which default to MariaDB. The password management is unnecessary as it is handled via socket activation.
=> Default to MariaDB packages on Debian releases after stretch

mysql/server.sls
Commit 89985f7485ccefd71b0bc6327fa732dc3c43d39d added a {% if ... %}
without the closing {% endif %} which leads to a Jinja syntax error.
This commit adds the missing {% endif %}
=> Fix unbalanced if/endif

mysql/defaults.yaml
python2-pymysql exists only in Leap 15 and Tumbleweed.
Up to Leap 42.3, the package is named python-pymysql.
=> Make SUSE package name compatible with Leap 42.x

mysql/config.sls, mysql/files/client.cnf, mysql/files/galera.cnf, mysql/files/my-include.cnf, mysql/files/my.cnf, mysql/files/mysql-clients.cnf, mysql/files/server.cnf
Using tpldir sent to templates through context.
=> Use tpldir for template files too

mysql/server.sls
Some usages of mysql.server in server.sls was not replaced with new mysql.serverpkg while updating map file.
=> Fixed mysql.server for new map file

mysql/files/client.cnf, mysql/files/galera.cnf, mysql/files/my-include.cnf, mysql/files/my.cnf, mysql/files/mysql-clients.cnf, mysql/files/server.cnf, mysql/server.sls
- The default config of `mysqld.datadir` and `mysqld.user` in FreeBSD (and others) is `None`.  `None` is not a valid config value in this context. a779417 fixes this.
- `cmd.run` accepts `user`, but ignores it. Only `runas` actually changes the UID.
Tested on FreeBSD 11.2.
=> Prevent None values in config files

mysql/files/mac_shortcut.sh, mysql/macos/install.sls, mysql/macos/remove.sls
This PR fixes "desktop shortcuts" on MacOS.
```
D: mysql-macos-workbench-desktop-shortcut-add
Function: cmd.run
Name: /tmp/mac_shortcut.sh add
Result: True
Comment: Command "/tmp/mac_shortcut.sh add" run
Started: 22:01:58.317289
Duration: 271.026 ms
Changes:   
----------
pid:
24010
retcode:
0
stderr:
stdout:
alias file MySQLWorkbench of folder Desktop of folder messi of folder Users of startup disk
ID: mysql-macos-community_server-desktop-shortcut-add
Function: cmd.run
Name: /tmp/mac_shortcut.sh add
Result: True
Comment: Command "/tmp/mac_shortcut.sh add" run
Started: 22:04:30.405989
Duration: 277.031 ms
Changes:   
----------
pid:
24066
retcode:
0
stderr:
stdout:
alias file mysql of folder Desktop of folder messi of folder Users of startup disk
```
=> Fix MacOS desktop shortcuts

pillar.example
At some point the key names were changed but the example wasn't updated as well.
=> Updated example pillar name overrides to match new keys

README.rst, mysql/config.sls, mysql/files/my-include.cnf, mysql/server.sls
These are some minor fixes for CentOS when using the yum repo from MariaDB upstream.
- Fix my-include.conf so it's possible again to have an empty global configuration. Otherwise the values defined in defaults.yaml are almost impossible to get rid of if you don't want them
- Package name can be 'mariadb-server' (distro package) or 'MariaDB-server' (MariaDB upstream package)
- Make sure the config directory and files under it are also only handled after the server package is installed, and not just /etc/my.cnf
=> Some minor fixes for CentOS

mysql/user.sls
Also allow creating users with SSL if they have non-database specific access to the server
=> Add support for user creation with SSL when no databases are defined

mysql/defaults.yaml, mysql/server.sls
PR to resolve issue [cannot install mysql](https://askubuntu.com/questions/1098074/mysql-fails-to-install-on-ubuntu-18-10) and probably [cannot create /var/lib/mysql](https://askubuntu.com/questions/1091843/mysql-cant-install-on-ubuntu-18-04-becasue-it-cant-create-directory-var-lib-mys) issue too.
```
ID: mysqld-service-running
Function: file.append
Name: /etc/apparmor.d/local/usr.sbin.mysqld
Result: True
Comment: Appended 2 lines
Started: 06:12:02.143185
Duration: 945.954 ms
Changes:   
----------
diff:
--- 
+++ 
@@ -0,0 +1,2 @@
+/var/lib/mysql/ r,
+/var/lib/mysql/** rwk,
...
ID: mysqld-service-running
Function: service.running
Name: mysql
Result: True
Comment: Service restarted
Started: 06:12:03.117972
Duration: 3082.849 ms
Changes:   
----------
mysql:
True
```
=> Apparmor support

mysql/init.sls
Was testing the formula and found that the extend in init.sls was calling for the wrong `id`
=> fix init.sls extend

mysql/user.sls, pillar.example
Closes #111 
This is pretty much a remake of #112, but now the escape argument only gets to be used when database info is specified for a user. It also includes an entry using the wildcard in the `pillar.example` for the foo database.
=> Allow the use of wildcards on a user's database/table names when defining grants.

pillar.example
It wasn't obvious to me how to enable this in the formula so I thought I'd document it for others.
=> Include pillar example for granting permissions to user on Any host

mysql/database.sls, mysql/user.sls, pillar.example
Adds the ability to remove
- a DB
- a DB user (user-host tuple to be specific)
Tested on FreeBSD 11.2 with Salt 2019.2, Python 3.6, MySQL 5.6.
Includes documentation in `pillar.example`.
=> Remove DB and/or user

mysql/defaults.yaml, pillar.example, test/salt/pillar/mysql.sls
The `enabled` has to be set in `defaults.yaml`, as mentioned in the comments of the other two files.
=> fix(connector): fix typos (connnector) and missing `enabled`

mysql/osfamilymap.yaml, mysql/osmap.yaml, mysql/repo.sls, mysql/server.sls
This PR fixes general jinja rendering errors on Archlinx - no `osmajorrelase` grain.
=> feat(linux): archlinux support (no osmajorrelase grain)

.travis.yml, .yamllint, mysql/defaults.yaml, mysql/osfamilymap.yaml
* Semi-automated using https://github.com/myii/ssf-formula/pull/27
* Fix (or ignore) errors shown below:
```bash
mysql-formula$ yamllint -s .
./mysql/osfamilymap.yaml
46:14     error    empty value in block mapping  (empty-values)
66:14     error    empty value in block mapping  (empty-values)
67:14     error    empty value in block mapping  (empty-values)
68:16     error    empty value in block mapping  (empty-values)
69:17     error    empty value in block mapping  (empty-values)
70:16     error    empty value in block mapping  (empty-values)
87:7      error    empty value in block mapping  (empty-values)
216:14    error    empty value in block mapping  (empty-values)
217:17    error    empty value in block mapping  (empty-values)
./mysql/defaults.yaml
29:10     error    empty value in …
```
=> ci(yamllint): add rule `empty-values` & use new `yaml-files` setting

mysql/files/mac_shortcut.sh
---
No.
Needs to be merged ASAP, so that the builds no longer fail, e.g. #232.
Fix these errors:
```bash
In mysql/files/mac_shortcut.sh line 5:
if [[ -e "{{ home }}/{{ user }}/Desktop/{{ app }}" ]] && [[ "${1}" -eq "remove" ]]
^------^ SC2154: remove is referenced but not assigned.
In mysql/files/mac_shortcut.sh line 8:
elif [[ -e "{{ dir }}/{{ app ~ '.app' if suffix else app }}" ]] && [[ "${1}" -eq "add" ]]
^---^ SC2154: add is referenced but not assigned.
```
CC: @noelmcloughlin.
N/A.
Travis lint job passes.
=> fix(mac_shortcut.sh): fix `shellcheck` errors

mysql/apparmor.sls, mysql/client.sls, mysql/config.sls, mysql/database.sls, mysql/dev.sls, mysql/disabled.sls, mysql/init.sls, mysql/macos/install.sls, mysql/python.sls, mysql/remove_test_database.sls, mysql/repo.sls, mysql/salt-user.sls, mysql/server.sls, mysql/user.sls
---
No.
none
A simple style PR to remove whitespace blocks with Jinja directives, to ease debugging.
-
-
=> style: remove previous line from jinja directives

mysql/osfamilymap.yaml, mysql/server.sls
---
No.
Current default version for FreeBSD is MySQL 5.7, also python 2.x is
deprecated and should be removed any time soon.
FreeBSD uses the `mysql_install_db` which generates a temporary root
password upon the first start. To the best of my understanding I haven't
seen any code in the formula that handles this method. So I added
a FreeBSD-scpecific block for initialization. While here, create
`/var/log/mysql` without which the server won't start if it doesn't
exist.
=> fix(FreeBSD): upgrade to mysql57-server

mysql/salt-user.sls
---
No.
Follow up to #260
More complete fix for #230 
This is embarrassing :(
I swear I tested the previous pull requests, but I just finished setting up a couple more servers and ran into these issues...
- For some onlyif conditions, the stderr redirect was part of the query sent to mysql, which obviously doesn't work
- The onlyif condition to check grant privileges returns an error string (to stderr) if we still need to execute the state. Redirecting that to stdout yields a false result for the condition and the state to set the grants is never executed. This is fixed by sending stderr to /dev/null. That way stdout response would still be captured, but we don't get false positives from errors.
=> fix(salt-user): fix setting grants for the salt user
