saltstack-formulas/mysql-formula

mysql/defaults.yaml
mysql/disabled.sls

Adds Fedora 21 support via mariadb.

Add Fedora 21 and a mysql.disabled state

---

mysql/remove_test_database.sls

Small syntax error fix in remove_test_database

Fix syntax error in mysql.remove_test_database

---

mysql/defaults.yaml
mysql/server.sls
mysql/supported_sections.yaml

Updated opensuse support to latest version of opensuse.

added opensuse support

---

pillar.example

The value of False does not work for me on Ubuntu Vivid. Using '' everything works as expected.

Update root_password example to use ''

---

README.rst
mysql/defaults.yaml
mysql/files/my.cnf
mysql/init.sls
pillar.example
scripts/import_users.py

Split out trailing whitespace fixes from #96 and include other files as well.

Fix trailing whitespaces.

---

mysql/database.sls
mysql/remove_test_database.sls
mysql/user.sls

Sorry, missed that yesterday :/

Fix wrong variable name for the salt user password in some files.

---

mysql/user.sls

Replace deprecated iteritems() with items()

---

mysql/defaults.yaml

fix defaults.yaml to support mysql5.7

---

mysql/user.sls
pillar.example

This might not be the best way to do SSL require on user creation. If anyone that is used to work in this mysql formula can do a better job then please do.

Added support for require SSL on user creation

---

mysql/server.sls

This pull request addresses issue #124 where the root password is generated randomly upon service start in MySQL 5.7+
This is addressed by requiring that the database be initialized with the new --intialize-insecure option on Arch and Redhat. This is a non-issue on Debian as debconf configures the root password before service startup.

Check for MySQL 5.7 and act appropriately on Redhat/Arch

---

mysql/server.sls
pillar.example

If pillar option for datadir exists will create in said directory

Made datadir dynamic

---

mysql/server.sls

Fix server.sls version check on Debian

---

.gitignore
.kitchen.docker.yml
.kitchen.yml
.travis.yml
Gemfile
Rakefile
pillar.example

Initial configuration of automated tests

---

mysql/defaults.yaml

Most of it was fixed recently but some parameters got missed.

Fixes for bad defaults on CentOS 7

---

mysql/defaults.yaml

python-MySQL-python has been replaced with python2-PyMySQL

fix python package suse

---

mysql/database.sls
pillar.example

This code is backwards compatible with the existing pillars (see pillar.example)
Solves #78

Added charset and collate support when creating database

---

mysql/database.sls

Avoid -p option if password is empty.

---

.kitchen.yml
.travis.yml

Update testing environment

---

README.rst
mysql/defaults.yaml
mysql/files/mac_shortcut.sh
mysql/macos/init.sls
mysql/macos/install.sls
mysql/macos/remove.sls
mysql/osmap.yaml
mysql/server.sls
pillar.example

This PR introduces `mysql.macos` and `mysql.macos.remove` states for MacOS software downloaded from  http://downloads.mysql.com.  States are verified on High Sierra.
```
ID: mysql-macos-workbench-remove-destdir
Function: file.absent
Name: /Applications/MySQLWorkbench.app
Result: True
Comment: Removed directory /Applications/MySQLWorkbench.app
Started: 23:55:20.337435
Duration: 329.152 ms
Changes:   
----------
removed:
/Applications/MySQLWorkbench.app
----------
ID: mysql-macos-community_server-remove-destdir
Function: file.absent
Name: /Applications/MySQL.app
Result: True
Comment: File /Applications/MySQL.app is not present
Started: 23:55:20.666758
Duration: 0.346 ms
Changes:   
----------
ID: mysql-macos-remove-entry-in-/etc/hostconfig
Function: file.line
Name: /etc/hostconfig
Result: …
```

Add install/remove states for MacOS

---

mysql/apparmor.sls
mysql/server.sls

This PR add a `apparmor.sls` state which can be executed alone.

Add server.apparmor state

---

mysql/server.sls

Make apparmor standalone state

---

mysql/macos/install.sls

It is wasteful downloading fresh archive if cached one already exists (with valid checksum).
This PR implements the improvement.

Only download archive if necessary [macos]

---

mysql/repo.sls

Fix typo in repo.sls

---

.travis.yml
.yamllint
mysql/defaults.yaml
mysql/map.jinja
mysql/osfamilymap.yaml
mysql/osfingermap.yaml
mysql/osmap.yaml
pillar.example
test/integration/default/inspec.yml
test/salt/pillar/mysql.sls

* Semi-automated using `ssf-formula` (v0.5.0)
* Fix (or ignore) errors shown below:
```bash
mysql-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
./mysql/osfamilymap.yaml
4:1       warning  missing document start "---"  (document-start)
5:6       error    syntax error: found character '%' that cannot start any token
94:17     error    trailing spaces  (trailing-spaces)
191:89    error    line too long (90 > 88 characters)  (line-length)
./mysql/defaults.yaml
3:1       warning  missing document start "---"  (document-start)
7:4       error    syntax error: found character '%' that cannot start any token
44:89     error    line too long (93 > 88 characters)  (line-length)
51:89     error    line too long (111 > 88 characters)  (line-length)
58:89     error    line …
```

feat(yamllint): include for this repo and apply rules throughout

---

mysql/osfamilymap.yaml

* there is no python2 in last stable releases and socket was moved as well
---
No.
Updated requirements and configuration for SUSE

fix(osfamilymap.yaml): Update SUSE defaults

---

.travis.yml
kitchen.yml
mysql/osfingermap.yaml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/209

feat(focal): add settings for `ubuntu-20.04` & use latest pre-salted images

---

mysql/user.sls
pillar.example

---
No.
None
Allow the creation of user with the `unix_socket` plugin.
```yml
mysql:
user:
myuser:
host: localhost
unix_socket: true
```
```yml
mysql_user_myuser_localhost:
mysql_user.present:
- name: myuser
- host: 'localhost'
- allow_passwordless: True
- unix_socket: True
- connection_host: 'localhost'
- connection_user: 'root'
- connection_pass: 'admin'
- connection_charset: utf8
```

feat(socket_authentication) Allow user to authenticate with unix_socket plugin

---

mysql/server.sls

---
No.
This is a followup on #250.
The patch I sent here suffered from a case of bad copy-n-paste and
missed half a level of indentation. Sorry.

fix(indent): properly indent file.directory block

---

pillar.example

---
No.
To rely on stricter ANSI SQL settings and have sane defaults, include explicit_defaults_for_timestamp=1 in your my.cnf under [mysqld] in `pillar.example`.

doc(example): update pillar.example for strict ansi

---

mysql/server.sls

---
- [X ] `[fix]`      A bug fix
No.
#255 
Proposed fix from code

fix(server.sls): fix dictionary startswith

---

mysql/salt-user.sls

---
No.
May fix #230
When commands used in the onlyif condition had output on STDERR, the condition wouldn't evaluate correctly.
A redirect of STDERR to STDOUT fixed the conditions for me and now the states work again as intended.

fix(salt-user): redirect error output from user access checks

---

mysql/osfamilymap.yaml

---
No.
for freebsd  update packages from `py37-*` => `py38-*`

feat(freebsd): update packages from ``py37-*`` => ``py38-*``

---

mysql/server.sls

---
No.
The indentation in servers.sls was unclear and made following the
control flow much harder.
Fix that by correctly indenting.
Drive-By: Change {% to {%- no-line-break opening tags for variable logic

refactor(jinja): improve indentation
